services:
  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'

  collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    restart: always
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: [ "--config=/otel-config.yaml" ]
    ports:
      - "4317:4317" #grpc
      - "4318:4318" #http
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app

  loki:
    depends_on:
      - grafana
    image: grafana/loki:main
    restart: always
    ports:
      - "3100:3100"
    command:
      -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

volumes:
  grafana-storage: {}
  loki: {}
  prometheus-data: {}