receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
          endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed

  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/logs]
